type: object
required: [className, attrs]
properties:
  className:
    type: string
    enum:
      - Rect
      - Circle
      - Ellipse
      - Text
      - Line
      - Image
      - Arrow
      - Star
      - Path
      - Group
      - RegularPolygon
      - Arc
      - Ring
      - Wedge
    example: Rect
  attrs:
    type: object
    required: [id]
    properties:
      id:
        type: string
    additionalProperties: true
  children:
    type: array
    items:
      type: object
