openapi: 3.1.0
info:
  title: Webster API
  description: API documentation for Webster backend
  version: 0.1.0

servers:
  - url: http://localhost:6767
    description: Local development server

security: []

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access
    refreshCookieAuth:
      type: apiKey
      in: cookie
      name: refresh

  schemas:
    # shared
    Errors:
      $ref: './spec/shared/Errors.yaml'
    PaginationLinks:
      $ref: './spec/shared/PaginationData.yaml'

    # auth
    LoginByEmail:
      $ref: './spec/auth/schemas/LoginByEmail.yaml'
    Registration:
      $ref: './spec/auth/schemas/Registration.yaml'
    Account:
      $ref: './spec/auth/schemas/Account.yaml'

    # profile
    UpdateProfile:
      $ref: './spec/profile/schemas/UpdateProfile.yaml'
    Profile:
      $ref: './spec/profile/schemas/Profile.yaml'
    ProfileData:
      $ref: './spec/profile/schemas/ProfileData.yaml'
    ProfilesCollection:
      $ref: './spec/profile/schemas/ProfilesCollection.yaml'

    # project
    CreateProject:
      $ref: './spec/project/schemas/CreateProject.yaml'
    UpdateProject:
      $ref: './spec/project/schemas/UpdateProject.yaml'
    Project:
      $ref: './spec/project/schemas/Project.yaml'
    ProjectData:
      $ref: './spec/project/schemas/ProjectData.yaml'
    ProjectsCollection:
      $ref: './spec/project/schemas/ProjectsCollection.yaml'
    ProjectMember:
      $ref: './spec/project/schemas/ProjectMember.yaml'
    ProjectMemberData:
      $ref: './spec/project/schemas/ProjectMemberData.yaml'
    ProjectMembersCollection:
      $ref: './spec/project/schemas/ProjectMembersCollection.yaml'
    UpdateMember:
      $ref: './spec/project/schemas/UpdateMember.yaml'
    ProjectInvite:
      $ref: './spec/project/schemas/ProjectInvite.yaml'
    ProjectInviteData:
      $ref: './spec/project/schemas/ProjectInviteData.yaml'
    SendInvite:
      $ref: './spec/project/schemas/SendInvite.yaml'

    # canva
    CreateCanva:
      $ref: './spec/canva/schemas/CreateCanva.yaml'
    UpdateCanva:
      $ref: './spec/canva/schemas/UpdateCanva.yaml'
    Canva:
      $ref: './spec/canva/schemas/Canva.yaml'
    CanvaData:
      $ref: './spec/canva/schemas/CanvaData.yaml'
    CanvasCollection:
      $ref: './spec/canva/schemas/CanvasCollection.yaml'

paths:
  # auth
  /webster/v1/accounts/registration:
    $ref: './spec/auth/paths/Registration.yaml'
  /webster/v1/accounts/login:
    $ref: './spec/auth/paths/LoginByEmail.yaml'
  /webster/v1/accounts/login/google:
    $ref: './spec/auth/paths/LoginByGoogle.yaml'
  /webster/v1/accounts/login/google/callback:
    $ref: './spec/auth/paths/LoginByGoogleCallback.yaml'
  /webster/v1/accounts/logout:
    $ref: './spec/auth/paths/Logout.yaml'
  /webster/v1/accounts/refresh:
    $ref: './spec/auth/paths/Refresh.yaml'
  /webster/v1/accounts:
    $ref: './spec/auth/paths/MyAccount.yaml'
  /webster/v1/accounts/me/verify-email:
    $ref: './spec/auth/paths/VerifyEmail.yaml'
  /webster/v1/accounts/me/verify-email/confirm:
    $ref: './spec/auth/paths/VerifyEmailConfirm.yaml'

  # profiles
  /webster/v1/profiles:
    $ref: './spec/profile/paths/FilterProfiles.yaml'
  /webster/v1/profiles/me:
    $ref: './spec/profile/paths/MyProfile.yaml'
  /webster/v1/profiles/me/avatar:
    $ref: './spec/profile/paths/MyProfileAvatar.yaml'
  /webster/v1/profiles/{account_id}:
    $ref: './spec/profile/paths/ProfileById.yaml'
  /webster/v1/profiles/@{username}:
    $ref: './spec/profile/paths/ProfileByUsername.yaml'

  # projects
  /webster/v1/projects:
    $ref: './spec/project/paths/Projects.yaml'
  /webster/v1/projects/invites/{token}/accept:
    $ref: './spec/project/paths/AcceptInvite.yaml'
  /webster/v1/projects/{id}:
    $ref: './spec/project/paths/ProjectById.yaml'
  /webster/v1/projects/{id}/members:
    $ref: './spec/project/paths/ProjectMembers.yaml'
  /webster/v1/members/{member_id}:
    $ref: './spec/project/paths/ProjectMemberById.yaml'
  /webster/v1/projects/{id}/invites:
    $ref: './spec/project/paths/ProjectInvites.yaml'

  # canvases
  /webster/v1/projects/{projectId}/canvases:
    $ref: './spec/canva/paths/Canvases.yaml'
  /webster/v1/projects/{projectId}/canvases/{id}:
    $ref: './spec/canva/paths/CanvaById.yaml'
